In [18]:
#Q1 Write a Python program to create an array of 5 integers and display the arra
 # Access individual element through indexes
import numpy as np
mylist=[1,2,3,4,5]
my_array=np.array(mylist)
my_array[4]

5

In [24]:
#Q2 Write a Python program to reverse the order of the items in the array
new_array = np.array
i=int(0)
for i in range(my_array):
    new_array[i] = my_array[5-i]
return new_array


TypeError: only integer scalar arrays can be converted to a scalar index

In [21]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
array_num.reverse()
print("Reverse the order of the items:")
print(str(array_num))


Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Reverse the order of the items:
array('i', [3, 9, 1, 7, 3, 5, 3, 1])


In [22]:
np.flip(my_array, axis =0)

array([5, 4, 3, 2, 1])

In [40]:
#Q3 Create a 4X2 integer array and Prints its attributes
#The shape of an array.
#Array dimensions.
#The Length of each element of the array in bytes.
array1 = np.array([[1,2],[2,1],[0,2],[1,0]])
print(array1.shape, array1.ndim, array1.itemsize)

(4, 2) 2 4


In [44]:
#Q4 return array of items in the third column from all rows in the following nump
array2=np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
array3=array2[:,2]
print (array2,array3)

[[11 22 33]
 [44 55 66]
 [77 88 99]] [33 66 99]


In [58]:
#Q5 Create a result array by adding the following two NumPy arrays
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
array_result = arrayOne + arrayTwo
array_result


array([[20, 39, 33],
       [25, 25, 28]])

In [61]:
#Q6 Sort the previous array
new_array=np.array
new_array= np.sort(array_result)
new_array

array([[20, 33, 39],
       [25, 25, 28]])